# Generated by Django 3.2.22 on 2023-10-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_actiove',
            new_name='is_active',
        ),
    ]
